### ISSUE TITLE
Octokit.repos.createLabel

### ISSUE THREAD

**Issue by louislai** [octokit/octokit.js#1005]
Hi, I was looking for an api to create a new label on a repo (not a new issue, equivalent to https://developer.github.com/v3/issues/labels/#create-a-label), but could not find it. Any plans to implement it in the near future? :-)

**Comment by eknowles** [comment]
do you mean _topics_? there is `Github.repos.replaceTopics`

```
  export type ReposReplaceTopicsParams = {
    owner: string;
    repo: string;
    names: string[];
  };
```

**Comment by kkweon** [comment]
What you're describing is indeed

```js
// ENDPOINT: /repos/:owner/:repo/labels
const result = await octokit.issues.createLabel({owner, repo, name, color, description})
```

https://octokit.github.io/rest.js/#api-Issues-createLabel

Although the function is in `octokit.issues`, it is not really related to issues (I'm saying because I think that's where you got this misconception)

> Hi, I was looking for an api to create a new label on a repo (**not a new issue**, equivalent to https://developer.github.com/v3/issues/labels/#create-a-label), but could not find it. Any plans to implement it in the near future? :-)



This is supposed to create a new label. 

The reason is in `octokit.issues` because a label belongs to the "**issue**" category as you can see in the URL https://developer.github.com/v3/ **issues** /labels/#create-a-label

**Comment by louislai** [comment]
@kkweon Awesome! I was indeed barking up the wrong tree. Thanks a lot :-)
