### ISSUE TITLE
PullRequestsGetResponse missing assignees and requested_reviewers

### ISSUE THREAD

**Issue by billytrend** [octokit/octokit.js#1048]
Not documented in github docs but `pullRequests.get` seems to return extra fields eg `assignees` and `requested_reviewers` (possibly others).

Not sure if this is within the scope of this project to include fields in types that are not even documented in github docs but thought I'd file the issue just in case. Thanks.

**Comment by gr2m** [comment]
it's not directly within the scope of this project, but as soon as it gets fixed in the docs it will automatically get fixed via [octokit/routes](https://github.com/octokit/routes). Could you please [ping support about it](https://github.com/support) and keep us posted here? They are very responsive and will forward your inquiry to the right team.

**Comment by billytrend** [comment]
sure
