### ISSUE TITLE
TS2304: Cannot find name 'AsyncIterableIterator'

### ISSUE THREAD

**Issue by ranyitz** [octokit/octokit.js#1189]
👋 Hey!

When running `tsc` I now get a new error. (starting from version `16.7.0`)

```
node_modules/@octokit/rest/index.d.ts(168,10): error TS2304: Cannot find name 'AsyncIterableIterator'.
```

In order to fix it, I needed to add `ESNext.AsyncIterable` to `tsconfig` `lib` option.

It's a breaking change and it's not clear from the docs that it should be added.

**Comment by gr2m** [comment]
👋 Hey Ran, thanks for opening the issue!

I wouldn’t consider typescript changes as breaking changes because they only occur on build times, not in production.

The new Typescript additions describes the ability for async iterators when paginating

```js
for await (const response of octokit.paginate.iterator(options)) {
  // do whatever you want with each response, break out of the loop, etc.
}
```

You don’t have to use the feature, but if you do Typescript will no longer complain.

Is there anything I can add to make this error go away, or do you have to add the configuration on your side?

**Comment by gr2m** [comment]
After researching this for a bit, I guess the answer to the error is to add `esnext.asynciterable` to `"lib": []` option in the `tsconfig.json` file

```json
{
  "lib": ["esnext.asynciterable"] 
}
```
