### ISSUE TITLE
Usage with axios

### ISSUE THREAD

**Issue by brunolemos** [octokit/octokit.js#1235]
I see you mentioned this code in another place: 

```js
const axios = require('axios');
github.hook.wrap('request', (request, options) => {
  return axios(options)
})
```

But it's not enough to make it work.
For example, need to rename the `baseUrl` option to `baseURL`. The `:repo`, `:owner` fields etc needs to be replaced with their respective values. And I get some errors like `Refused to set unsafe header "user-agent"`. 

Any full working solution for axios?

**Comment by gr2m** [comment]
Just curious, why do you want to use axios?

Can you try this?

```js
const axios = require('axios');
github.hook.wrap('request', (request, options) => {
  return axios(request.endpoint.parse(options))
})
```

I think one problem is that `github.hook.wrap` adds a wrapper around the current request, as the name suggests. But the request options might be changed in previous wrappers, e.g. the authentication header is set that way. 

In order to replace the request method, I’m considering to add a `fetch` option, to which you can pass a function with the signature of [fetch](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Syntax). But I’d like to understand the use cases better when people need it. On such use case is testing, e.g. using [fetch-mock](http://www.wheresrhys.co.uk/fetch-mock/)

**Comment by brunolemos** [comment]
> Just curious, why do you want to use axios?

I was going to reuse their interceptors, but since octokit now supports hooks too I'm using it (just had to duplicated some code).

**Comment by brunolemos** [comment]
> Can you try this?

`Cannot read property 'parse' of undefined`

**Comment by gr2m** [comment]
Sorry I’m on mobile right now, I didn’t test it myself. Try github.request.endpoint.parse(options)

**Comment by brunolemos** [comment]
Almost there. The access token is not being included in the requests, so I get authorization error. And also a `Refused to set unsafe header "user-agent"` in the console.

**Comment by gr2m** [comment]
As I mentioned in https://github.com/octokit/rest.js/issues/1235#issuecomment-460362339, it sets authentication after you call the request method. As you don’t call the passed request method, it won’t set it at all. Hence the idea of a `fetch` option (`new Octokit({fetch})`). 

> I was going to reuse their interceptors

What for exactly? Anything that you cannot do with Octokit itself?

**Comment by brunolemos** [comment]
Thanks.

As I mentioned in https://github.com/octokit/rest.js/issues/1235#issuecomment-460365748, the reason is to reuse the axios interceptors, but since octokit now also supports interceptors I don't really need to make it use axios, I can use octokit hooks and duplicate some code (https://github.com/devhubapp/devhub/commit/bf355e13ab05802aa4d029b0ec84254764677c28).

But since it wasn't possible to make axios work I opened an issue :)
