### ISSUE TITLE
How do you use Github plugins in browser?

### ISSUE THREAD

**Issue by davidtlee** [octokit/octokit.js#1261]
I was wondering how Github plugins can be used in browsers as opposed to in Node? The syntax in the docs says to use syntax like the following:
```
const Octokit = require('@octokit/rest')
  .plugin(require('@octokit/plugin-retry'))
```

This seems to be the syntax when using `require` as in the instructions for Node. How do you use plugins when downloading octokit through a script tag in the browser (see screenshot of instructions below for setting up Octokit in Node vs. Browser in docs).

![image](https://user-images.githubusercontent.com/863081/53653187-99876f80-3bff-11e9-83a4-fbf1c93d8afc.png)

Thanks!

**Comment by gr2m** [comment]
In order to make it work, the plugin needs to be bundled for browser usage first I’m afraid. It’s something we should do but don’t yet.

It’d be a similar setup as it is in this repository:

### 1. Install as dev dependencies

- compression-webpack-plugin
- npm-run-all
- webpack
- webpack-bundle-analyzer
- webpack-cli

### 2. Add 4 scripts to `package.json`.

Replace `octokitPluginRetry` and `octokit-plugin-retry` with the correct name in case you don’t do it for the retry plugin.

```json
  "scripts": {
    [...]
    "build:browser": "npm-run-all build:browser:*",
    "build:browser:development": "webpack --mode development --entry . --output-library=octokitPluginRetry --output=./dist/octokit-plugin-retry.js --profile --json > dist/bundle-stats.json",
    "build:browser:production": "webpack --mode production --entry . --plugin=compression-webpack-plugin --output-library=octokitPluginRetry --output-path=./dist --output-filename=octokit-plugin-retry.min.js --devtool source-map",
    "generate-bundle-report": "webpack-bundle-analyzer dist/bundle-stats.json --mode=static --no-open --report dist/bundle-report.html",
  }
```

### 3. Configure [semantic-release](https://semantic-release.gitbook.io/semantic-release/) `package.json` to automatically upload the assets to each release

```json
  "release": {
    "publish": [
      "@semantic-release/npm",
      {
        "path": "@semantic-release/github",
        "assets": [
          "dist/*",
          "!dist/*.map.gz"
        ]
      }
    ]
  },
```

### 4. In `.travis.yml`, add the build steps before semantic-release

```diff
-      script: npx semantic-release
+      script:
+        - npm run build:browser
+        - npm run generate-bundle-report
+        - npm run semantic-release
```

After that, each new GitHub release should have the browser builds attached.

Would you like to send a pull request to add that to the plugins you need?

**Comment by davidtlee** [comment]
Thanks @gr2m for the detailed instructions. I don't know much (anything) about webpack and bundling, but this might be the time to learn. I'll take a stab in a couple weeks (or ask a friend to try).

**Comment by gr2m** [comment]
I’ll close the issue for now, but I’ll keep in mind to make it easier to consume plugins in the browser without the necessity of a build step. If you have more questions feel free to comment
