### ISSUE TITLE
🤔 Got questions about APIs for the new GitHub Package Registry?

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1362]
Just announced: https://www.youtube.com/watch?v=GkV0M7SN7vI

Learn more at https://github.com/features/package-registry and https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry

There are no new REST/GraphQL APIs for the new GitHub Package Registry at this point. The npm registry implements the same API surface as https://registry.npmjs.org/, so existing clients such as https://github.com/npm/npm-registry-client. There is no changes feed for the npm registry as of yet. 

API-related questions only please 🙏 For general questions, please contact support@github.com

**Comment by manuelbieh** [comment]
How do you avoid package name confusion e.g. when I publish a package named `myawesomepackage` to your registry and somebody else publishes another package with the same name to npm. How do I make sure to always install the correct package from the correct registry? Do I, as a package maintainer, have to publish my packages to two different registries from now on? Or do you somehow make it possible to mirror every package I publish to pkg.github.com to npm?

Excited as I am for the new registry I am also a bit worried about the possible confusion that might lead to.

// edit:
I know I can change the default registry in `.npmrc` and `.yarnrc` of course. I'm just wondering what happens if I need packages from both npm and GPR.

**Comment by gr2m** [comment]
For general questions about the registry, better to ask support@github.com.

This repository is for the REST API client for JavaScript, I’ve opened this issue as I expect folks to ask questions such as: "how can I list the most recent releases using the REST API."

**Comment by manuelbieh** [comment]
Oh sorry, then the title of the issue is a bit misleading 😉

**Comment by gr2m** [comment]
GitHub’s npm registry allows to edit the description of packages, that is not something that npm’s registry supports. I wonder if there will be an API endpoint for that?

![](https://user-images.githubusercontent.com/39992/57561412-63bde000-7340-11e9-8fc9-012d6b196120.png)
