### ISSUE TITLE
Debouncing search in documentation

### ISSUE THREAD

**Issue by soonoo** [octokit/octokit.js#1383]
It seems searching in gh-pages is little bit laggy.
How about debouncing search function or processing it in web worker?
(Will it be an overkill?)

I want to work on it if possible.

By the way, thank you for the nice software😺

**Comment by gr2m** [comment]
> How about debouncing search function or processing it in web worker?

I would _love_ if the search would run in a webworker. But I don’t know how to make it work. We are using this Gatsby Plugin: https://github.com/gatsby-contrib/gatsby-plugin-elasticlunr-search

And here is the custom JavaScript code that does the UI:
https://github.com/octokit/rest.js/blob/master/docs/src/components/search.js

The heavy load is the initial creation of the search index:
https://github.com/octokit/rest.js/blob/ade2d00dd0642a4205ab3a7714106003db820f68/docs/src/components/search.js#L64

And the actual search:
https://github.com/octokit/rest.js/blob/ade2d00dd0642a4205ab3a7714106003db820f68/docs/src/components/search.js#L94-L96

**Comment by SGrondin** [comment]
I'd start with debouncing. I suggest doing it manually, but if you think it's worth using a library, feel free to reach out to me on the [Probot Slack](https://probot-slackin.herokuapp.com/) so it's done using the same library that the [throttling plugin](https://github.com/octokit/plugin-throttling.js) uses because it's extremely important to keep the package size small.

Debouncing is likely to be enough, but it will depend on the CPU intensiveness of the full text search. Most of the time Webworkers are overkill because it takes more work just to copy the data in and out of the worker than to do the work. However you might be able to use [ownership transfer](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Passing_data_by_transferring_ownership_(transferable_objects)) to avoid this issue, and full text search is often fairly CPU intensive.

It's possible that only the initial [indexing](https://github.com/octokit/rest.js/blob/ade2d00dd0642a4205ab3a7714106003db820f68/docs/src/components/search.js#L64) will benefit from Web workers. Make sure to benchmark the gains for indexing and for searching separately.

But please start with debouncing because it might be enough. Good luck! Feel free to reach out to me if you have questions.

**Comment by soonoo** [comment]
Actually I tried debounced version before opening this issue, but there was no such a big effect. 

After that I've found below `setState` causes lag:
https://github.com/octokit/rest.js/blob/ade2d00dd0642a4205ab3a7714106003db820f68/docs/src/components/index-page.js#L24-L28

Above `onSearch` is called in:
https://github.com/octokit/rest.js/blob/ade2d00dd0642a4205ab3a7714106003db820f68/docs/src/components/search.js#L88

Responsiveness becomes faster after removing `this.props.onSearchQuert(query)`.
Is it okay to remove that code line?

Also it seems render function is a bottleneck rather than search function. Although time was measured, it may be inaccurate.

**Comment by gr2m** [comment]
@SGrondin all this code is about the documentation only, none of it goes into the `@octokit/rest` codebase :)

@soonoo  maybe start a pull request? It will be easier for us to test your changes

**Comment by soonoo** [comment]
I'm working on it and will open pull request soon.

**Comment by soonoo** [comment]
Closed by PR #1387
