### ISSUE TITLE
Wrong typings on GistsGetResponse

### ISSUE THREAD

**Issue by protiumx** [octokit/octokit.js#1411]
Hi guys.
I've noticed that the field **files** is type `GistsGetRevisionResponseFiles`
```js
type GistsGetRevisionResponseFiles = {
    "hello_world.rb": GistsGetRevisionResponseFilesHelloWorldRb;
    "hello_world.py": GistsGetRevisionResponseFilesHelloWorldPy;
    "hello_world_ruby.txt": GistsGetRevisionResponseFilesHelloWorldRubyTxt;
    "hello_world_python.txt": GistsGetRevisionResponseFilesHelloWorldPythonTxt;
  };
```

but it should be an object with fields of type
```js
{
    filename: string;
    type: string;
    language: string;
    raw_url: string;
    size: number;
    truncated: boolean;
    content: string;
  };
```

I temporarily fixed this changing the typing 
```js
interface IFixGistResponse extends Omit<Octokit.GistsGetResponse, "files"> {
  files: any | GitHubApi.GistsGetResponseFiles;
}
```
version "5.1.8"

**Comment by wolfy1339** [comment]
This is an interesting issue. These typings are automatically generated from data in `@octokit/routes`.
The issue would most likely lie there, if the data is correct.

**Comment by protiumx** [comment]
I imagined that. Looking at this [https://developer.github.com/v3/gists/#get-a-single-gist](https://developer.github.com/v3/gists/#get-a-single-gist) the problem is that the Gists API returns files as an Object instead of an Array. A possible solution would be defining the type as follow
```js
interface GistFile {
    filename: string;
    type: string;
    language: string;
    raw_url: string;
    size: number;
    truncated: boolean;
    content: string;
  };
interface GistsGetResponseFiles {
    [key: string]: GistFile
}

interface GistsGetResponse {
...
files: GistsGetResponseFiles 
}
```

**Comment by gr2m** [comment]
As @wolfy1339 mentioned, these types are currently generated automatically, we do not currently implement exceptions. We generate the types from the example responses on https://developer.github.com/v3/.

We are currently migrating octokit/routes to an OpenAPI specification format via https://github.com/octokit/routes/pull/168. There is a chance that GitHub might adapt it as its "source of truth" for both the REST API documentation as well as the source to generate REST API clients such as `@octokit/rest`. Once we get there, we will stop scraping documentation websites and instead edit the OpenAPI spec directly. That will allow us to implement exceptions such as this one.

In this particular case I think it was a poor API decision to return an object instead of an array of objects, but I guess we are stuck with that for now ¯\\\_(ツ)\_/¯

**Comment by protiumx** [comment]
I agree. I've tried to fix it in your **generate_types.js** scripts but the lib you are using for types generation does not support typescript's **Index Signature**.

I'm closing the issue
