### ISSUE TITLE
Add optional preview headers to documentation

### ISSUE THREAD

**Issue by jeffrafter** [octokit/octokit.js#1487]
I was trying to use `draft: true` on the pull request create and noticed that the resulting pull request wasn't a draft. I think this is because the create pull request API requires `application/vnd.github.shadow-cat-preview+json` for that to work:

https://developer.github.com/v3/pulls/#create-a-pull-request

There are a couple of other useful preview headers there as well.

Unfortunately the route for creating a pull request doesn't list any `headers`: https://github.com/octokit/rest.js/blob/master/plugins/rest-api-endpoints/routes.json#L2702-L2715

Would be happy to pull-request this...

**Comment by gr2m** [comment]
Hey Jeff, we only set required preview headers, not the optional ones. I'm still conflicted about how to handle the preview headers, there is no consensus. I still plan to log a message that a preview header was set for you, because API endpoints might change without notice while in preview (even though that is not happening a lot in practise).

Also the optional preview headers should totally be listed in the docs: https://octokit.github.io/rest.js/#octokit-routes-pulls-create I'd very happily accept a pull request for that 🙏 

What you need to do is this

```js
octokit.pulls.create({
  mediaType: {
    previews: ['shadow-cat']
  },
  draft,
  owner,
  repo,
  title,
  head,
  base
})
```

**Comment by jeffrafter** [comment]
Oh, I like the API here. I'll put together a pull for the docs. 🙌

**Comment by jeffrafter** [comment]
I noticed there is documentation here: https://github.com/octokit/rest.js/blob/master/docs/src/pages/api/02_introduction.md. Do you think listing the available previews for a given endpoint should be per-route?

Also, I tried using `mediaType` and noticed that it is not listed in TypeScript

![](https://rpl.cat/uploads/nfH-edPd8lj8BGXK-Xj-_oAyQ8b7twZ8YbYkgAWjp8g/public.png) - it is possible my types are just outdated?

**Comment by jeffrafter** [comment]
Oh I see that was added in 16.30 (https://github.com/octokit/rest.js/releases/tag/v16.30.1) looks like GitHub's toolkit is behind. Will bump there.

**Comment by gr2m** [comment]
Yes I think it got lost when we migrated to the new OpenAPI-spec based octokit/routes, but it should all be good again. Let me know if something is still not working as expected
