### ISSUE TITLE
Generic, read-only authentication

### ISSUE THREAD

**Issue by stdavis** [octokit/octokit.js#1501]
I'm building a CLI that is for the general public to use that needs read-only access to all public repositories. What's the best way to authenticate ocotokit/rest.js so that I don't hit rate limits? I can't use a personal access token since this will be a publicly available tool. I'd rather not ask my users to log in with GitHub creds via OAuth since it only needs read access to public repos. Are there any other options?

Thanks for the great project.

**Comment by gr2m** [comment]
If you only need read access to public repositories then a personal access token or an OAuth token without any scopes will suffice. 

You can ask your users to create a token at https://github.com/settings/tokens/new without checking any of the checkboxes. Then they have to pass that token to your CLI somehow, that will give the CLI 5000 requests / hour (instead of 50).

A little more convenient for the user would be if you created an OAuth app and the users would authenticate using a web flow, but that would require you to host a little server, as the OAuth client_secret should be kept, well, secret :) You can use that library for the server: https://github.com/octokit/auth-oauth-app.js

Does either of these work for you?

**Comment by stdavis** [comment]
I was hoping for another alternative that didn't require the user to authenticate or generate a personal access token. Sounds like that's not an option. I'll give your oauth recommendation a try. Thank you very much for the detailed response.

**Comment by gr2m** [comment]
You could create a separate GitHub account and create a token with that, then hardcode the token into the CLI. The problem here is that every user would share the same rate limit, and it only takes one bug or one abusive user to ruin it for everyone.

**Comment by stdavis** [comment]
I can see how that would be an issue.

**Comment by gr2m** [comment]
Let me know if you have any question. I have a plan :tm: to make it easier for developers to build CLI tools with JavaScript and Octokit. Mostly consisting of two parts:

1. A generic OAuth secrets keeper service. It would have a simple UI to add your OAuth app's secrets. It's to get you started quickly, once the project takes off, you should host your own version.
2. A UI to which OAuth apps can redirect to. The target would be a static website. The CLI would temporarily open a port on localhost and set it to the `state` in the OAuth web flow. After the direct, the static website would send the code to the port number using the `state` parameter. Once the CLI retrieves the code, it closes the port again.

**Comment by stdavis** [comment]
That sounds like exactly what I would use. Have you started yet? I'd be happy to help if you've got something already going.

**Comment by gr2m** [comment]
Nothing ready yet, no. Maybe we can start on the 2nd part? I can help you setup an instance for `1.` manually, it's pretty easy, I used https://github.com/HenrikJoreteg/github-secret-keeper in the past.

I've created an org for `2.`: https://github.com/CLI-login, so that way we can have a nice URL for it once we build it: https://cli-login.github.io.

Let me create the `cli-login.github.io` repository and invite you to it :)
