### ISSUE TITLE
Feature Request: Create Pull Request with template in .github folder

### ISSUE THREAD

**Issue by kevo1ution** [octokit/octokit.js#1502]
Feature details:
- Create a pull request with a template from .github folder https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository

Motivation:
- I don't want to require more permissions for my github bot to view the content of the repo to get the pull request template.

**Comment by gr2m** [comment]
I'm sorry I'm not exactly sure what you would want to do? Are you looking for a method to create a pull request but using the pull request template title and body instead of setting it yourself?

I don't think that is possible with [today's REST API endpoints](https://developer.github.com/v3/), but you could [create a plugin](https://octokit.github.io/rest.js/#plugins) which looks for the pull request template and defaults title/body based on it when creating a pull request?

**Comment by kevo1ution** [comment]
Yes, I am trying to create a pull request using the pull request template title and body that is .github/pull_request_template.md (this file is assumed to be different for each repo that the bot is installed on). 

Because I am trying to restrict the permissions that my Github Bot needs, I wanted a way to create a pull request from the template without needing content read access. I assume that even if I create a plugin, the bot will need content read access.
