### ISSUE TITLE
total_count is deprecated in pagination

### ISSUE THREAD

**Issue by skeggse** [octokit/octokit.js#1514]
I'd like to propose that, for resources that provide it, we support a means for both paginating and simultaneously getting the `total_count` field from the response (with perhaps the caveat that the total count won't match the count of items produced by the end of the pagination).

The use case I have in mind is a small CLI tool that performs bulk actions on some set of issues or pull requests, and prompts the user to confirm the scope of the bulk changeset by printing the number of matched issues/pull requests. I could make a separate API call, but I tend to prefer optimizing these cases (yeah, I know, premature optimization...).

Feel free to close this if you feel this isn't worth supporting - I just noticed it was deprecated and it didn't seem like there was much discussion around it in #1289.

**Comment by gr2m** [comment]
I think I will un-deprecate `total_count` for the responses that provide it, as there is currently no alternative way to retrieve it. But it's only available for the following endpoints:

- https://developer.github.com/v3/search/#example
- https://developer.github.com/v3/checks/runs/#response-3
- https://developer.github.com/v3/checks/suites/#response-1
- https://developer.github.com/v3/apps/installations/#list-repositories
- https://developer.github.com/v3/apps/installations/#list-installations-for-a-user

If you need the total_count for other responses, I'd suggest to contact support@github.com so that they can track the request. That information could be added as a response header, for example.

**Comment by skeggse** [comment]
Not stale.

**Comment by gr2m** [comment]
Hey Eli, the `.total_count` and other properties  (`.incomplete_results` and `.incomplete_results`) are no longer considered deprecated.

By the way, if you want to get a total count ahead of a pagination request, you can send a `HEAD` request with `?per_page=1` and then check the `Link` response header. Note that the `Link` header is not set if there is no more than one page in total.

☝️😉 Encapsulating this logic would make a sweet little plugin
