### ISSUE TITLE
Latest release of library does not export types (as expected)

### ISSUE THREAD

**Issue by bcoe** [octokit/octokit.js#1589]
Installing the latest version of `@octokit/rest`, I'm seeing a lot of TypeScript compilation errors:

```bash

src/github.ts:18:3 - error TS2305: Module '"../node_modules/@octokit/rest"' has no exported member 'AnyResponse'.

18   AnyResponse,
     ~~~~~~~~~~~

src/github.ts:19:3 - error TS2305: Module '"../node_modules/@octokit/rest"' has no exported member 'IssuesListResponseItem'.

19   IssuesListResponseItem,
     ~~~~~~~~~~~~~~~~~~~~~~

src/github.ts:20:3 - error TS2305: Module '"../node_modules/@octokit/rest"' has no exported member 'PullsListResponseItem'.

20   PullsListResponseItem,
     ~~~~~~~~~~~~~~~~~~~~~

src/github.ts:21:3 - error TS2305: Module '"../node_modules/@octokit/rest"' has no exported member 'ReposListTagsResponseItem'.
```

I'm attempting to import the types thusly:

```js
import {
  AnyResponse,
  IssuesListResponseItem,
  PullsListResponseItem,
  ReposListTagsResponseItem,
  Response,
} from '@octokit/rest';
```

I'm also seeing this issue upstream in a library using probot:

```bash
node_modules/probot/lib/application.d.ts:18:23 - error TS2694: Namespace '"/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/node_modules/@octokit/rest/index"' has no exported member 'Static'.

18     Octokit?: Octokit.Static;
                         ~~~~~~

node_modules/probot/lib/github/index.d.ts:5:45 - error TS2694: Namespace '"/usr/local/google/home/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/probot/node_modules/@octokit/rest/index"' has no exported member 'Static'.

5 export declare const ProbotOctokit: Octokit.Static;
                                              ~~~~~~
```

**Comment by gr2m** [comment]
Instead of 

```js
import {
  AnyResponse,
  IssuesListResponseItem,
  PullsListResponseItem,
  ReposListTagsResponseItem,
  Response,
} from '@octokit/rest';
```

do

```js
import { Octokit } from '@octokit/rest';
```

Then use 


```js
Octokit.AnyResponse
Octokit.IssuesListResponseItem
Octokit.PullsListResponseItem
Octokit.ReposListTagsResponseItem
Octokit.Response
```

The default export is deprecated. In JavaScript, you'll see a deprecation message. I tried to keep both working for TypeScript, too, but to no avail. Sorry for the trouble, there was no perfect solution for it, and I don't consider TypeScript changes breaking changes, as they only affect build times. At least until we add official Deno support :)

**Comment by bcoe** [comment]
Appreciate the quick response @gr2m (and the awesome software).

Some user feedback from using probot in a mono-repo, with octokit as a dependency of some of our libraries, we've bumped in to a lot of breaking changes in types which has made upgrading hard and frightening.

I would happily take on more breaking changes, i.e., have to upgrade from probot `9.9.1` -> `10.0.0` vs., TypeScript changes in minors and patches.

I also understand that software is a series of tradeoffs, and that you likely have reasons for some of the breaking changes that have landed. _For starters, I understand that TypeScript is a gray area._

**Comment by gr2m** [comment]
I'm sorry to hear all the trouble with Probot and upgrading :(

To give you some context and perspective. The probot code is quite the mess :)

It was written in TypeScript before any of the Octokit libraries were. And it implemented some functionalities that only slowly were created proper in seperate Octokit libraries. 

Probot code is still a mess but I think we have all the pieces together to clean it up properly now. When done, I hope probot to be a very slight wrapper around Octokit libraries, basically a chef's recommendation for building GitHub Apps with Node.js. That should greatly reduce the current friction between Probot and the Octokit libraries.

The Probot upgrade path will not be easy, but at least it will all be contained in Probot.

The migration of Octokit to TypeScript will be complete with the [upcoming v17 release](https://github.com/octokit/rest.js/issues/1546), that should remove friction caused by discrepancies between code & type definitions.

**Comment by bcoe** [comment]
@gr2m appreciate the work you're putting in. It sounds like things are moving in a great direction. I think we partially made things hard for ourselves because one of our bots relies on octokit externally from probot.
