### ISSUE TITLE
Get repo by ID

### ISSUE THREAD

**Issue by MitchK** [octokit/octokit.js#163]
The endpoint `/repositories/:id` is not documented on GitHub, but it is available. 

Example: https://api.github.com/repositories/20633049

Also PyGithub uses this (https://github.com/jacquev6/PyGithub/blob/b64b0d6942bb27095bd035b8c0db10ca35448be3/github/MainClass.py) and I would like to also have it for Node.js

We need this, because the `user/repo` is not a good identifier for a unique repo, since repo names can be changed, username can be changed and ownership can be moved.

**Comment by gr2m** [comment]
Hi @Londane 

You can get a repository by ID using `octokit.request`

```js
octokit.request('GET /repositories/:id', {id})
```

See the "BREAKING CHANGES" section for the [v16 release](https://github.com/octokit/rest.js/releases/tag/v16.0.1).

We removed a dedicated method because it’s not documented on https://developer.github.com/v3/ either. I think it’s being discussed to make it "official" as integrators depend on it, once it does, we will add a method again.

If you want to add the previous method back, you can do it using a plugin

```js
const Octokit = require('@octokit/plugin')
  .plugin((octokit) => {
    octokit.registerEndpoints({
      repos: {
        getById: {
          method: 'GET',
          url: '/repositories/:id',
          params: {
            id: {
              type: 'string',
              required: true
            }
          }
        }
      }
    })
  })

const octokit = new Octokit()

octokit.repos.getById({id: 123})
```

**Comment by busch-matthias** [comment]
> Hi @Londane
> 
> You can get a repository by ID using `octokit.request`
> ...

Thank your very much for your help! 
Your code will help me a lot!

**Comment by SpencerKaiser** [comment]
@gr2m for what it's worth, I desperately needed `/repositories/:id` last year for a company event and had no idea that it existed until now... if you have some situation where you are monitoring a set of repos, you totally lose access to a repo if the name is changed, so retrieving by ID is the only real way around that. I would love to see this functionality re-introduced and see the docs updated...
