### ISSUE TITLE
Octokit docs' link to GitHub Dev Docs 404

### ISSUE THREAD

**Issue by IAmHughes** [octokit/octokit.js#1657]
After reading through the [Octokit rest docs](https://octokit.github.io/rest.js/v17), looking at any endpoint has a link to the [GitHub Developer docs](https://developer.github.com/v3/). As shown in this screenshot, there is an issue with this link being generated and leads to a 404:

![image](https://user-images.githubusercontent.com/2894107/77550059-a1efbf80-6e7e-11ea-92a8-8eb78cd3424d.png)

It is linking to `https://octokit.github.io/rest.js/endpoint.documentationUrl` on every link in every endpoint's documentation.

/cc @gr2m for input ❤️

**Comment by gr2m** [comment]
Oopsie, thank you for reporting the issue! The endpoint method descriptions are actually coming from https://github.com/octokit/plugin-rest-endpoint-methods.js/tree/master/docs, so the problem needs to be fixed there. The problem is in this line:

https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/a14c70e579559243da6e2d20aada0a9a91807e17/scripts/update-endpoints/docs.js#L86

Would you like to send a pull request to fix it? No worries if not, I can take care of it, no problem

**Comment by IAmHughes** [comment]
> Would you like to send a pull request to fix it?

Thanks @gr2m, I'll PR it. Taking a look now 🎉, may ping you for some noodling on it.

**Comment by IAmHughes** [comment]
> I'll PR it. Taking a look now 🎉, may ping you for some noodling on it.

[PR Created](https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/57) ✔️

**Comment by gr2m** [comment]
This is not yet fix, I still need to update `@octokit/plugin-rest-endpoint-methods` to v3.3.3. That will happen once Greenkeeper sends its pull request
