### ISSUE TITLE
createTree fails sometime with 404 error.

### ISSUE THREAD

**Issue by YoEight** [octokit/octokit.js#1686]
Greetings,

As weird as it sounds, I can't find a better description for what we are experiencing. 90% of the time,
we call `createTree`, everything works. However, from time to time, we end up with the very helpful 404 error code. We know it isn't an authentication error because it shouldn't have worked those previous times.

This is how we use `createTree` in our GitHub action: https://github.com/EventStore/Automations/blob/master/changelog-update/index.js#L216

This is what we get when it fails: https://github.com/EventStore/EventStore/pull/2426/checks?check_run_id=584937366

We are using `v17` octokit version.

Thank you for your time.

**Comment by gr2m** [comment]
Hmm it looks like the request was not authenticated at all 🤔 Here are the headers that were sent for the create a tree request: https://github.com/EventStore/EventStore/pull/2426/checks?check_run_id=584937366#step:4:33. There should be `authorization` among them, with a redacted token, but there is not.

First thing I would do is to replace `@actions/github` with [`@octokit/action`](https://github.com/octokit/action.js). Then you won't need to load `@octokit/rest` separately, because `@octokit/action` is always up to date, I maintain it myself.

Could you try that first, please?

My guess would be that for some reason `const auth = core.getInput('github-token');` does not return a token in some cases.

**Comment by gr2m** [comment]
Oh actually I think I know what the problem is: https://github.com/EventStore/EventStore/pull/2426/checks?check_run_id=584937366#step:4:33 is triggered by a pull request coming from a fork. Actions triggered by forks do not have access to the secrets you defined, for security reasons.

**Comment by YoEight** [comment]
@gr2m Thank you very much for your feedback! I checked and indeed, that error always happens when the pull request is from a fork! It makes a lot of sense, thanks to your explanation.

I will move our code to `@octokit/action`
