### ISSUE TITLE
getRef always failing in latest v18.0.5 with HttpError - Not Found 404

### ISSUE THREAD

**Issue by lipika** [octokit/octokit.js#1862]
Here is my code to call getRef in 18.0.5. I have reverted to 16.25.4 version to make it work. Difference between 2 version is the way git url being auto generated. In 16 version git url - <org git_url>/git/refs/heads/master, but in 18 version  <org git url>/git/**ref**/heads%2Fmaster.  

```js
clientWithAuth.git.getRef({
    owner: gitOwner,
    repo: gitRepo,
    ref: 'heads/master'
  })
```

Response -

```json
{
   "name":"HttpError",
   "status":404,
   "headers":{
      "access-control-allow-origin":"*",
      "access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type",
      "connection":"close",
      "content-encoding":"gzip",
      "content-security-policy":"default-src 'none'",
      "content-type":"application/json; charset=utf-8",
      "date":"Wed, 09 Sep 2020 20:01:56 GMT",
      "referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin",
      "server":"GitHub.com",
      "status":"404 Not Found",
      "strict-transport-security":"max-age=31536000; includeSubdomains",
      "transfer-encoding":"chunked",
      "x-accepted-oauth-scopes":"repo",
      "x-content-type-options":"nosniff",
      "x-frame-options":"deny",
      "x-github-enterprise-version":"2.18.5",
      "x-github-media-type":"github.v3; format=json",
      "x-github-request-id":"",
      "x-oauth-scopes":"delete_repo, repo",
      "x-runtime-rack":"0.111586",
      "x-xss-protection":"1; mode=block"
   },
   "request":{
      "method":"GET",
      "url":"<org git url>/git/ref/heads%2Fmaster",
      "headers":{
         "accept":"application/vnd.github.v3+json",
         "user-agent":"octokit/rest.js v1.2.3 octokit-rest.js/18.0.5 octokit-core.js/3.1.2 Node.js/10.15.3 (win32; x64)",
         "authorization":"token [REDACTED]"
      },
      "request":{
         
      }
   },
   "documentation_url":"https://developer.github.com/enterprise/2.18/v3"
}",""pid""\":41140}"
```

**Comment by gr2m** [comment]
Hi @lipika, the ` /git/ref/*` endpoints were introduced as a replacement for the `/git/refs/*` endpoints. 

Until GitHub Enterprise 2.18, we had these endpoints

1. [`GET /repos/{owner}/{repo}/git/refs/{ref}`](https://docs.github.com/en/enterprise/2.18/user/rest/reference/git#get-a-reference)
2. [`GET /repos/{owner}/{repo}/git/refs/{namespace}`](https://docs.github.com/en/enterprise/2.18/user/rest/reference/git#get-all-references)

You can see the two routes are technically the same. The problem was that you couldn't predict a response. The response could be

- a 404
- an object,
- an array

Since GitHub Enterprise Server 2.19, we have

1. [`GET /repos/{owner}/{repo}/git/ref/{ref}`](https://docs.github.com/en/rest/reference/git#get-a-reference)
2. [`GET /repos/{owner}/{repo}/git/matching-refs/{ref}`](https://docs.github.com/en/rest/reference/git#list-matching-references)

If you cannot upgrade your GHES version, you can use this plugin which works around the problem:
https://github.com/octokit/plugin-enterprise-compatibility.js

But note that GHES 2.18 is no longer supported

**Comment by gr2m** [comment]
I'll close the issue because it's not a bug, but please feel free to comment if you have more questions
