### ISSUE TITLE
Link to best practices for integrators 404s

### ISSUE THREAD

**Issue by filmaj** [octokit/octokit.js#1882]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

N/A

**Versions**

**What happened?**

The link to 'best practice for integrators' under the [Throttling section](https://octokit.github.io/rest.js/v18#throttling) 404s

**Minimal test case to reproduce the problem**

Head to https://octokit.github.io/rest.js/v18#throttling, click the link, see an 'Oops' page

**What did you expect to happen?**

Not see a 404

**What the problem might be**

The link in https://github.com/octokit/rest.js/blob/master/docs/src/pages/api/09_throttling.md is probably outdated

**Comment by gr2m** [comment]
Thanks a lot for filing the issue @filmaj. You are correct, the link needs to be fixed in https://github.com/octokit/rest.js/blob/master/docs/src/pages/api/09_throttling.md . The correct link is https://docs.github.com/en/rest/guides/best-practices-for-integrators. Would you like to send a pull request to resolve it?

**Comment by filmaj** [comment]
Sure! Opened https://github.com/octokit/rest.js/pull/1884
