### ISSUE TITLE
Caching Solution

### ISSUE THREAD

**Issue by ekristen** [octokit/octokit.js#215]
@mikedeboer thanks for the awesome library. 

I really needed caching support and I thought about adding caching support into the library, but found that a significant portion of the httpSend would have to be rewritten, so I wrote a module that extends your module and adds caching support.

https://github.com/ekristen/node-github-cache

Just wanted to let you know, thought you may be open to referencing it in your project. If not feel free to delete the issue from existence. No hard feelings. 

Thanks again for the awesome module.

**Comment by petersandor** [comment]
Just needed something like this, and it works flawlessly, thanks @ekristen!

**Comment by ekristen** [comment]
I didn't like self advertising on here, but wanted to let others know there was a solution. Glad it worked for you @petersandor

**Comment by piglovesyou** [comment]
Hello folks, from the distant future in 2025. I'm impressed by this attempt when even though this project was maintained under an individual namespace. I wanted a caching solution as well, and for the API interface today, it turned out we could simply pass a customised fetch function with a wrapper.

I'll leave what met my need as a snippet, with the hope that it helps someone in the future in any form. To make it more generic, it would need additional tweaks such as "cache only when HTTP GET", which it would be awesome if someone can compose a shippable Oktokit Plugin or anything.

https://gist.github.com/piglovesyou/8141ea2d776f7a0da300c097e9de8489
