### ISSUE TITLE
Get Branch API request returns main instead master or 404

### ISSUE THREAD

**Issue by sijjay** [octokit/octokit.js#2200]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

Make https://octokit.github.io/rest.js/v18#repos-get-branch request with option: 'branch': 'master'

### Please select the environment(s) that are relevant to your bug report

- [ ] TypeScript
- [x] Enterprise
- [ ] Browsers
- [X] Node
- [ ] Deno

### Version

octokit - 18.12
node.js - 14.4.0

### What happened?

Hi team,
I want to rename a branch name thru api, but first i need to check, if this branch is exist.
Vy repo has default branch anme 'main', but i'm looking for 'master'.
When i trying to make 
```
octokit.rest.repos.getBranch({
  owner,
  repo,
  branch: 'master,
});
```
it returns me data about 'main' branch.

But original Github API request returns "Moved permanently" with url to 'main' branch.

Is it possible not to do a redirect?

![image (2)](https://user-images.githubusercontent.com/83004945/153430424-f4637b4f-270d-49d6-81f9-61c2b4a5f24f.png)
![image (3)](https://user-images.githubusercontent.com/83004945/153430446-b628e491-7b02-401a-a14b-e11b723b5a0e.png)

### Would you be interested in contributing a fix?

- [X] yes

**Comment by oscard0m** [comment]
Hi @sijjay !

After checking the documentation of Octokit, I can see that the default behavior is to follow the redirects of GitHub API response.

Still, I can see it exists an option to change this default behavior:
https://github.com/octokit/request.js/blob/master/src/fetch-wrapper.ts#L10

but it's not working for me (as you can see in this example): https://runkit.com/dominguezcelada/octokit-request-with-redirect-error

---

@gr2m @wolfy1339 @timrogers when running this request and debugging we are losing the `redirect` option when it's passed down, not sure if it is because of a bug or a misusage of the option.

When the execution reaches this point, `options.redirect` is defined:
https://github.com/octokit/endpoint.js/blob/52d83f8f309eb7779979dc5aef58d24e0c775275/src/parse.ts#L14

But, when the execution reaches this other point, `requestOptions.redirect` is undefined:
https://github.com/octokit/request.js/blob/bc060b070c2e40d488ade12bdb525db3cf896dea/src/fetch-wrapper.ts#L34-L40

Is it possible we are losing the property when returning the parsed options here?
https://github.com/octokit/endpoint.js/blob/52d83f8f309eb7779979dc5aef58d24e0c775275/src/parse.ts#L102-L106

**Comment by timrogers** [comment]
Has the branch been renamed already through the GitHub UI? It sounds like that is probably what has happened. 

As @oscard0m mentions, Octokit automatically follows redirects. There is meant to be a way to disable that behaviour - which is one way you couple work around this API behaviour - but it sounds like it isn’t working correctly. 

For now, could you check the branch name returned from `getBranch` to the one you requested? If it’s different, then it has already been renamed. That seems like a reasonable approach to me.

**Comment by timrogers** [comment]
@oscard0m That `parse` function looks pretty suspicious to me! 😅

**Comment by gr2m** [comment]
> After checking the documentation of Octokit, I can see that the default behavior is to follow the redirects of GitHub API response.
> 
> Still, I can see it exists an option to change this default behavior: https://github.com/octokit/request.js/blob/master/src/fetch-wrapper.ts#L10

The native behavior of `fetch` does not permit access to redirect responses for safety reasons. @sijjay are you testing in Node 18 by chance? It comes with native `fetch` built in, so it won't load `node-fetch`. 

And even when using `node-fetch`, I had problems with the `.redirect` option in the past, it didn't behave as I though it would.

If you want full access of the request lifecycle, you can get generic request options like this

```js
const { url, ...requestOptions } = octokit.rest.repos.getBranch.endpoint({
  owner,
  repo,
  branch: 'master,
});
```

And then pass these options into another request library such as [got](https://github.com/sindresorhus/got).

```js
// using with got (https://github.com/sindresorhus/got)
got[options.method](url, requestOptions);
```

With `got` you have full control over `3xx` redirect responses

**Comment by sijjay** [comment]
@gr2m 
Hi guys,
I'm sorry, but not. And I can't check it since the project is already closed (I implemented a workaround). 
But thanks a lot for the updates! It inspires hope, because support for the Octokit project is still on the fly))
