### ISSUE TITLE
Error when authenticating user with token

### ISSUE THREAD

**Issue by K9Developer** [octokit/octokit.js#2340]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

Not sure

### Please select the environment(s) that are relevant to your bug report

- [ ] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [X] Node
- [ ] Deno

### Version

octokit version: 2.0.10

imported: `import { Octokit, App } from "octokit";`

### What happened?

I'm trying to use Octokit with react native, so I installed it, this step goes well, then imported, this one too goes well, but when running `const octokit = new Octokit({ auth: token });` It errors and says:
```
Error: Unable to resolve module crypto from ... crypto could not be found within the project or in these directories:
```
What could be the problem?

(NodeJS version: 18.8.0)

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by gr2m** [comment]
This is most likely a problem with webpack bundling, I think there were a few issues in the past about it. `crypto` should not make it into the browser build. Maybe this issue will help? https://github.com/gr2m/universal-github-app-jwt/issues/38

**Comment by K9Developer** [comment]
> This is most likely a problem with webpack bundling, I think there were a few issues in the past about it. `crypto` should not make it into the browser build. Maybe this issue will help? https://github.com/gr2m/universal-github-app-jwt/issues/38

Hi, I'm VERY new to react native... I'm not even sure I know what a web pack is. Could you maybe walk me a bit through it?

**Comment by gr2m** [comment]
Unfortunately I don't have experience with React Native either. Webpack is used to bundle the code from `octokit` and its dependencies together with your React Native app's code, so that it can be run together on a device. But some dependencies such as https://github.com/gr2m/universal-github-app-jwt/ need to run different code for different environments (e.g. node or browsers). In your case, I assume React Native should get the browser code, but it bundles the Node code instead. When you want to run the app, you then get the error that the `crypto` module doesn't exist (which is a native Node module). 

I'm sorry I can't help better. I'm sure other folks used Octokit with React Native in the past, maybe look for open source projects for reference?

You can also try and use `@octokit/core` instead of `octokit`, as it doesn't have the dependency on  `universal-github-app-jwt` and hence shouldn't run into the particular problem you ran into

**Comment by K9Developer** [comment]
@gr2m Thanks, I will try using @octokit/core

EDIT: Thank you! It worked like a charm!!!
