### ISSUE TITLE
[FEAT]: Include `@octokit/request-error` in the bundle

### ISSUE THREAD

**Issue by DariuszPorowski** [octokit/octokit.js#2464]
### Describe the need

Nice to have `@octokit/request-error` as part of the bundle with re-exported `RequestError` instance for easy error handling in the typed projects.

```typescript
// import re-exported RequestError instance from @octokit/request-error
import { Octokit, RequestError } from 'octokit'

const octokit = new Octokit(...)

try {
  return await octokit.rest...({})
} catch (error) {
  if (error instanceof RequestError) {
    // handle Octokit error
  } else {
    // handle all other errors
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
Good idea 👍🏼

**Comment by DariuszPorowski** [comment]
Will prep PR

**Comment by DariuszPorowski** [comment]
@gr2m hmm trying to create PR, but something has changed on `@octokit/request-error` today's release:
- previous: https://unpkg.com/browse/@octokit/request-error@3.0.3/
- current: https://unpkg.com/browse/@octokit/request-error@4.0.0/
The current one doesn't expose type declarations :/

**Comment by wolfy1339** [comment]
I filed https://github.com/octokit/request-error.js/issues/337, I'll get around to fixing that.

We should really make note somewhere of what repos have the hotfix and how many have transitioned to esbuild to avoid pushing bad releases like in this case

You can copy the types from the latest `3.x` version for local dev until the issue is resolved
