### ISSUE TITLE
[FEAT]: support discussions

### ISSUE THREAD

**Issue by itaysk** [octokit/octokit.js#2489]
### Describe the need

support to interact with GitHub discussions. it has been discussed https://github.com/octokit/octokit.js/issues/886 but never implemented.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
We don't manually implement the methods. They are all automatically generated from GitHub's OpenAPI spec.

If they aren't present there, they won't be here either.

You can always use the route you want to use directly using `@octokit/request` (which is included in this package)

**Comment by gr2m** [comment]
> It has been discussed #886 but never implemented

The discussions endpoints hat have been discussed in this issue have been changed since, instead of `/teams/{team_id/...` it's now `/orgs/{org}/teams/{team_slug}/...`. The methods all exist on `octokit.rest.teams.*`, e.g. `octokit.rest.teams.getDiscussionInOrg()`.

Note that team discussions are being defunkt.
