### ISSUE TITLE
[BUG]: With next.js14(app directory) + Jest, Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jihea-park** [octokit/octokit.js#2729]
### What happened?

My app is made by next.js14 (app directory).
I tried to test my code with jest.
But I got errors.

### Versions

"octokit": "^4.0.2",
node: v20.17.0

### Relevant log output

```shell
● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/user/Desktop/platformAdminKit/platform-admin-kit-app/node_modules/octokit/dist-bundle/index.js:2
    import { Octokit as OctokitCore } from "@octokit/core";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      10 | const repo = oss?.repo;
      11 | const pat = process.env.NEXT_PUBLIC_OSS_PAT;
    > 12 |
         | ^
      13 | type GetRepoContentResponseType =
      14 |   Endpoints['GET /repos/{owner}/{repo}/contents/{path}']['response']['data'];
      15 | export type FileContentResponseType = GetRepoContentResponseType & {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (lib/hooks/oss.ts:12:18)
      at Object.<anonymous> (app/DataProvider.tsx:24:14)
      at Object.<anonymous> (app/UserInfoProviders.tsx:26:23)
      at Object.<anonymous> (components/User/UserTable.tsx:15:28)
      at Object.<anonymous> (__tests__/user.test.tsx:9:59)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Jest is really really bad.
It requires so much configuration for simple tasks like ESM.

We currently use vitest (as of 2024-12-29), instead of Jest in this repo, see the previous version of [`package.json`](https://github.com/octokit/octokit.js/blob/33d03d9ede478b425254dc9882cb7078622cd189/package.json) for the configuration

Octokit v4 is an ESM-only module.
See [this gist](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) on how to transition.

**Comment by chad-fossa** [comment]
I do not see a "jest" config in package.json, nor a jest.config.js file

**Comment by wolfy1339** [comment]
We switched from Jest over to Vitest for their native Typescript support

**Comment by wolfy1339** [comment]
Here is the `package.json` before the switch, https://github.com/octokit/octokit.js/blob/33d03d9ede478b425254dc9882cb7078622cd189/package.json

**Comment by chad-fossa** [comment]
Thank you.  There's quite a bit there and I understand why you switched over.

Switching to vitest is likely out of scope for me at the moment, though I'll consider it.

That said, I'm not 100% sure what to extrapolate from that file.  I can see your jest configuration:

```
  "jest": {
    "extensionsToTreatAsEsm": [
      ".ts"
    ],
    "transform": {
      "^.+\\.(ts|tsx)$": [
        "ts-jest",
        {
          "tsconfig": "test/tsconfig.test.json",
          "useESM": true
        }
      ]
    },
    "testPathIgnorePatterns": [
      "/docs/"
    ],
    "coverageThreshold": {
      ...
    },
    "moduleNameMapper": {
      "^(.+)\\.jsx?$": "$1"
    }
  },
```

Unfortunately I'm not 100% sure that this is going to be helpful for me.  I currently see this error:

```
   /me/mycode/project/node_modules/@octokit/rest/dist-src/index.js:2
    import { Octokit as Core } from "@octokit/core";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | // octokit v17 (github REST API v3)
    > 2 | import { Octokit } from '@octokit/rest';

```

And when I switch to "--experimental-vm-modules", the error changes to:

```

    Must use import to load ES Module: /Users/chadfurman/FOSSA/fossabot/node_modules/@octokit/rest/dist-src/index.js

      1 | // octokit v17 (github REST API v3)
    > 2 | import { Octokit } from '@octokit/rest';
        | ^
      3 |

```

I've tried multiple versions of tsconfig.json and jest.config.js and .babel.config.js over the last 7 hours.  My current version is:

```
// tsconfig.json

{
  "compilerOptions": {
    "strict": true,
    "allowJs": true,
    "module": "commonjs", // or ES2022
    "target": "ES2022",
    "esModuleInterop": true,
    "allowImportingTsExtensions": true
  },
  "include": ["src/**/*"]
}
```

```
// .babel.config.js

module.exports = {
  presets: [
    ['@babel/preset-env', {targets: {node: 'current'}}],
    '@babel/preset-typescript',
  ],
};
```

```
// jest.config.js

/** @type {import('ts-jest').JestConfigWithTsJest} **/
module.exports = {
  transform: {
    '^.+\\.(t|j)sx?$': ['ts-jest', {'useESM': true}],
  },
  transformIgnorePatterns: [ 'node_modules/(?!(@octokit/rest))' ],
  extensionsToTreatAsEsm: [ '.ts' ],
  moduleNameMapper: {
    '^(.+)\\.jsx?$': '$1'
  }
};
```

This is the result of me trying to pull values from the config file you linked -- your old package.json file.

What I'm finding is that somehow the octokit module wants to be transformed, and so I've tried "excluding from tranform ignore" with various regex and allowing js files since the octokit distributable has js files using "import" syntax and such.

It's worth noting that my "package.json" doesn't have the "`type: 'module'` configuration, and that adding it gives me a very-much-separate error (and likely will require a bit separate configuration etc).

I've also explored adding the "babel-jest" transform option, and I may be able to get some milage out of that if i "de-typsecript" my jest files, but at the moment I'm holding out hope I can somehow get ts-jest to run.  

I'm tempted to just mock out octokit completely; though there are some end-to-end tests that I'd actually like to run...

Any suggestions from your previous jest sufferings where you may be able to suggest what I'm doing wrong?

**Comment by wolfy1339** [comment]
> `SyntaxError: Cannot use import statement outside a module`

This error is because you are trying to use `import` statements in CJS code.

> `Must use import to load ES Module: /Users/chadfurman/FOSSA/fossabot/node_modules/@octokit/rest/dist-src/index.js`

This error is because it's transforming the `import` statement, and it's trying to `require()` an ESM-only module.

We don't require any transformations to use the Octokit code in Jest.

Since your code is CJS, you want to stick to v20 of `@octokit/rest` and pin it there. All the most recent major versions of Octokit packages are ESM-only

**Comment by chad-fossa** [comment]
Thank you I will stick to v20 and see if that helps!!!!!

**Comment by chad-fossa** [comment]
THAT FIXED IT!~ I love that.  You're a hero.  Thank you so much.  TIL
