### ISSUE TITLE
Add support for React Native

### ISSUE THREAD

**Issue by azzamallow** [octokit/octokit.js#273]
I attempted to use this package in an application I started building using React Native, unfortunately it did not work.

Requiring the package causes the react packager to hang.

```
var GitHubApi = require("github");
```

Pressing Command-R in the simulator produces (after about a minute):

```
Could not connect to the development server. Ensure node server is running and available on the same network - run 'nom start' from react-native root.

URL: http://localhost:8081/index.ios.bundle

The request timed out.
```

The packager hangs forever when attempting to debug.

I am told that not all packages run in React Native, mainly ones that designed specifically for Node JS (express for example).

**Comment by Talor-A** [comment]
In the meantime, there's [react-native-github-api](https://github.com/brunolemos/react-native-github-api), though you'll have to add it manually (pretty sure it's not on npm).

**Comment by machour** [comment]
Here's a more up to date fork, with a single commit to add the RN compatibility: https://github.com/machour/node-github/commit/1ef08ecc6b537f1d39dee84f4204358a2fb88f5a
cc @gr2m

**Comment by gr2m** [comment]
I removed the `fs` dependency from node-github. I know it’s been a while but could you @azzamallow or someone else give it a try with react native? I haven’t built anything with it myself yet.

If it still fails, it would be helpful to create a minimal repository that I could use for testing. I’d definitely like to make it work

**Comment by machour** [comment]
Gave it a try in a React Native app by just importing the lib in a screen:

`import gh from 'github';`

First error:
<img width="348" alt="screen shot 2017-12-28 at 7 23 12 pm" src="https://user-images.githubusercontent.com/304450/34419853-802c90dc-ec06-11e7-9164-df5842d48f89.png">

workaround: manually running `yarn add url` in my project

Second error:
<img width="347" alt="screen shot 2017-12-28 at 7 38 59 pm" src="https://user-images.githubusercontent.com/304450/34419918-c72a2292-ec06-11e7-9562-cdd3690b671b.png">

The culprit seems to be this line: https://github.com/octokit/node-github/blob/master/lib/index.js#L726

RN doesn't seem to have a polyfill for `http`. Would it be possible to use `fetch` instead?


By the way, wasted so much time by testing https://www.npmjs.com/package/node-github  instead of https://www.npmjs.com/package/github because of this repo name 😭😭😭😭  
Would it be possible to add a clear deprecation message when installing the old package, or something? 🙏

**Comment by gr2m** [comment]
Thanks for giving it a try!

`url` is not a module on npm, it’s one of Node’s core modules:
https://nodejs.org/api/url.html

> RN doesn't seem to have a polyfill for http. Would it be possible to use fetch instead?

We will most likely migrate to [node-fetch](https://www.npmjs.com/package/node-fetch) for the browser compatibility

> By the way, wasted so much time by testing https://www.npmjs.com/package/node-github instead of https://www.npmjs.com/package/github because of this repo name 😭😭😭😭
Would it be possible to add a clear deprecation message when installing the old package, or something? 🙏

I’m sorry for the trouble :(

We will rename this module soon to `@octokit/rest`, so that shouldn't happen again

**Comment by gr2m** [comment]
`@octokit/rest` is browser-compatible already. But I’m working towards smaller bundle sizes, including the use of `fetch` for browser targets. Maybe that’ll help with React Native, too? See updates here: https://github.com/octokit/rest.js/issues/620#issuecomment-362715478

**Comment by brunolemos** [comment]
React Native is a different environment than browser and node.
Made #1056 with a fix.

**Comment by gr2m** [comment]
Hey I know it's been a while, but I figured folks watching this thread might be interested.

The upcoming `@octokit/request` is dropping `node-fetch` as dependency altogether. You can pass a custom `fetch` function as `{ request: { fetch } }` option (see [options](https://github.com/octokit/request.js#request)). See https://github.com/octokit/request.js/pull/586

You can try it out with

```
npm install @octokit/request@beta
```
