### ISSUE TITLE
Saving commits in json variable with pagination

### ISSUE THREAD

**Issue by davidcdupuis** [octokit/octokit.js#285]
Hi, 

I actually have two questions.

So I just discovered your module. 
I'm working on an app to figure out what week has the most commits in a repository. 

I'm not very good with node.js yet. 
My first issue is saving the response value into a variable for later use in the code. 
var response = github.repos.getCommits({ 
    user: "mbostock",
    repo:'d3',
    since: "2014-10-15T08:54:11.973Z",
    per_page: 100,
    page : 2
}, function(err, res) {
  return res;
});

My second issue is understanding how to iterate through the pages to complete my response variable. I noticed your client_test.js but I don't understand what you coded. :(

Thanks for the help.

**Comment by kaizensoze** [comment]
`var x = github.repos.getCommits({ ... })` is actually setting a variable to the async request, which hasn't necessarily completed yet. If anything, you'll want to store the `res` variable in the `function(err, res)` callback. Any further calls or use of the variable would need to be done in the callback though or using promises since you need to wait for the `getCommits` call to finish.

For iterating over paginated results, see this [example](https://github.com/mikedeboer/node-github/blob/master/examples/getStarred.js).
