### ISSUE TITLE
Question about routes.json and upstream updates

### ISSUE THREAD

**Issue by ZauberNerd** [octokit/octokit.js#450]
Is the routes.json written by hand or generated / bootstrapped by some machine-readable
schema or screen scraping of the Github API website?

My search for a schema of the Github API has been mostly without luck - there are some
unofficial attempts to create a raml / swagger definition here:
- http://api-portal.anypoint.mulesoft.com/github/api/github-api-v3/github-api-v3.raml
- https://github.com/APIs-guru/unofficial_openapi_specs/blob/master/github.com/v3/swagger.yaml

Is there a plan to switch to an open standard (i.e. swagger)?
I have seen that some bootstrapping work has already been done in this branch:
https://github.com/mikedeboer/node-github/commit/8e8cc37a32713a166f2e204088c54c5635eb7048
Or should the routes.json be extended?

I have done some work here: https://github.com/ZauberNerd/node-github/commit/940318e3394e3f9c50ef437f3fa2821b9e53b9d1 to make the enum values in parameters more explicit, but haven't created a PR yet, because I wasn't sure if the routes.json is being generated or if it will potentially be replaced by a swagger file or similar.

I ask these questions because it would be helpful to have response models so that the
generated flow types could properly type the API responses.

**Comment by kaizensoze** [comment]
Yeah the routes.json is written by hand and pretty much the core of the lib along with index.js. It's a process of manually going through the github api website and comparing with the current routes.json to see if anything needs to be updated, along with watching the github api changes blog over at https://developer.github.com/changes/.

I'm open to adding the enum formalization changes in the routes.json; although another option is using the `allowedValues` apiParam property in apidoc (http://apidocjs.com/).

I had started on a swagger file in the apidoc-to-swagger branch but kinda abandoned it. Swagger would be nice, but not necessarily a priority since the apidoc, while not ideal, does the trick in showing what endpoints are available and their node-github lib equivalents, along with a homebrew search filter.

When I took up maintaining the repo there were a lot of endpoints missing so the priority was going through all the pull requests and issues, and adding/fixing any endpoints, with a focus on functionality. The current main glaring issues are no working tests and a lack of browserify compatibility. (Admittedly I feel like getting tests working at this point is a lost cause since I don't foresee myself manually creating them in the near future nor someone else going through all the endpoints and submitting a pull request.)

I haven't gone over the flowtypes PR yet. My only concern is that it would need to be manually updated along with any changes made to routes.json, correct?

**Comment by ZauberNerd** [comment]
The flow types are being generated from the routes.json.
There's a [template file written with mustache templates](https://github.com/ZauberNerd/node-github/blob/27390bd12a72ab255d7d2d0d80e89c3faf58648d/templates/index.js.flow.tpl) and a [`generateFlowTypes.js`](https://github.com/ZauberNerd/node-github/blob/27390bd12a72ab255d7d2d0d80e89c3faf58648d/lib/generateFlowTypes.js) that reads the routes.json in a similar way to the `generate.js` file (which now also calls the `generateFlowTypes.js`).
There's two things that I would like to improve here:
- first: [The array types should have more information about their contents](https://github.com/ZauberNerd/node-github/blob/27390bd12a72ab255d7d2d0d80e89c3faf58648d/lib/generateFlowTypes.js#L30).
- second: [The enum values are being parsed out of the regular expressions, which I would like to make more explicit](https://github.com/ZauberNerd/node-github/blob/27390bd12a72ab255d7d2d0d80e89c3faf58648d/lib/generateFlowTypes.js#L52) - I'll take a look at `allowedValues` of apidoc.

Also nice to have, but not that important to me right now, would be to have type information about the responses. I'll think a bit more about whether there is an easy way to do this or not.

What are your thoughts on testing? I mean it is possible to stub out `http` or use some tool to capture and compare "replays", but that only helps to verify that the payload is as expected - not that the request would actually work.
Does Github have a testing environment where changes could be made and reset to actually test the whole API? And would that make sense at all? Or would verifying the request payload be enough?

**Comment by kaizensoze** [comment]
Ah right, ok in that case I'll look into merging the flowTypes PR and feel free to create a PR for the routes.json enums changes. The enums field would be easier to parse than the apidoc allowedValues param, which would be more for documentation purposes. I'll create a separate PR adding allowedValues values.

The whole testing thing, regardless of something like nock, would be a pain in the ass for [modifying] endpoints based on the authorized user token's permissions. I'd need to think about the easiest way to implement it.

UPDATE: If you want me to merge the enum changes PR first and then modify the flowtypes PR to parse the enum values to save a PR, that's fine too.

**Comment by kaizensoze** [comment]
Going to close this and any possible work on tests or swagger can be made into other tickets.
