### ISSUE TITLE
Slashes in some params not translated properly

### ISSUE THREAD

**Issue by yotamshacham** [octokit/octokit.js#453]
Hi there, looks like slashes in the ref name are not handled properly, they are placed with %2F.

The calling code is call to update reference:

github.gitdata.updateReference({owner:"embroker", repo:"embroker",ref:"refs/heads/__codeship_e2e", sha: ...}, callback);

Request then looks like this:

REQUEST:  { host: 'api.github.com',
  port: 443,
  path: '/repos/embroker/embroker/git/refs/refs%2Fheads%2F__codeship_e2e',
  method: 'patch',
  headers: 
   { host: 'api.github.com',
     'content-length': 50,
     'content-type': 'application/json; charset=utf-8',
     Authorization: 'token XXXXXX',
     'user-agent': 'Embroker-Github-Service',
     accept: 'application/vnd.github.v3+json' },
  ca: undefined }
REQUEST BODY: {"sha":...}

Is there a workaround or something I'm missing?  Thanks.

**Comment by kaizensoze** [comment]
Yeah, just need to add an edge case to not encode the ref param. 

Also, this is annoying, but the ref value to enter shouldn't begin with "refs/". Annoying because when you call getReferences the ref values include "refs/", but the api endpoint in the docs is `/repos/:owner/:repo/git/refs/:ref` so to keep the library in sync with the official github doc you just need to remove the refs/ prefix.
