### ISSUE TITLE
gitdata.deleteReference failed with 404 error when use # sign in ref (branch name)

### ISSUE THREAD

**Issue by up73k** [octokit/octokit.js#499]
New versions of node-github (_in ver 3.x.x was ok_) gitdata.deleteReference is failed on # sign in "ref" with 404 (Error: "Not Found"). Other methods (creating and searching) with # sign is ok.
     
```
gitdata.deleteReference({
                owner: request.head.user.login,
                repo: request.head.repo.name,
                ref: `heads/some@another#other`
})
```

GitHub Enterprise 2.6

**Comment by kaizensoze** [comment]
Deleting a reference with a hash in it is pretty dangerous since hash is treated as a fragment identifier.

Ex: https://api.github.com/repos/kaizensoze/test2/git/refs/heads/a#blah

Right now the ref param value isn't being encoded since it's a path, but the fix might be to specifically escape hashes. I'm not sure if there are any gotchas that would make this a bad idea.

Definitely looking for input on this.

**Comment by kcampion** [comment]
Now you can do that:
```
git.getRef({
    owner: request.head.user.login,
    repo: request.head.repo.name,
    ref: `heads/some@another%23other`
})
```
