### ISSUE TITLE
Request to /login/oauth/access_token not found

### ISSUE THREAD

**Issue by joliejuke-orga** [octokit/octokit.js#500]
Hey,

I configured a callback on my server to get the request_token code.  

But I didn't find in the issues or docs if node-github support the request to the route:
`https://github.com/login/oauth/access_token`

This route send me back an access_token with the given code.
Best.

**Comment by kaizensoze** [comment]
The library doesn't handle the oauth callback stuff. It just assumes you have a token [or other authentication means] and has the various authenticate methods. Or you can create a token using `github.authorization.create`.

See here: https://github.com/mikedeboer/node-github#authentication.

**Comment by kaizensoze** [comment]
Closing soon if no reply.

**Comment by pastudan** [comment]
I am struggling with the same issue due to what seems like inconsistencies in the documentation. When reading through https://developer.github.com/v3/guides/basics-of-authentication/#providing-a-callback, it states:
> Note that you'll probably never access the API through REST. For a more serious application, you should probably use a library written in the language of your choice.

However, https://github.com/octokit/rest.js/issues/500#issuecomment-277021645 states that this library does not handle the oauth callback.

So, am I supposed to make my own request just for the `access_token`, but for everything else, use this library? If so, could we update the documentation on the web to reflect that? Thanks!

**Comment by gr2m** [comment]
@pastudan could you please create a new issue? It will make it easier for us to track it. Let’s discuss there

**Comment by qngapparat** [comment]
For anyone struggling with this, `https://github.com/login/oauth/access_token` returns a 404 if the headers aren't set.

Solution:

```js
fetch('https://github.com/login/oauth/access_token', {
    method: 'POST',
    body: JSON.stringify({
      ...bodyParams, 
      client_id: clientId
      client_secret: clientSecret
    }),
    headers: { <---
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
  })
```

**Comment by gr2m** [comment]
For OAuth flows, we have a module with different methods that should cover all common use cases:
- https://github.com/octokit/oauth-methods.js/

We have authentication strategies for OAuth Apps and OAuth users:
- https://github.com/octokit/auth-oauth-app.js
- https://github.com/octokit/auth-oauth-user.js

and an SDK for building OAuth Apps:
- https://github.com/octokit/oauth-app.js
