### ISSUE TITLE
Get content raw media type

### ISSUE THREAD

**Issue by pdashford** [octokit/octokit.js#507]
Hi, I'm using the get content api to get a specific file, however I have seen you can use a media type so that the raw file data is returned can you advise how I would use the media type in the call?

` github.repos.getContent({
        owner: owner,
        repo: repo,
        path: path
    }, function (err, res) {
        console.log(err, res);
    });`

**Comment by kaizensoze** [comment]
You can add an accept header to the params of the request, so:

```js
github.repos.getContent({
    owner: owner,
    repo: repo,
    path: path,
    headers: {
        "Accept": "application/vnd.github.v3.raw"
    }
}, function (err, res) {
    console.log(err, res);
});
```

**Comment by pdashford** [comment]
Many thanks that sorted it.

**Comment by orta** [comment]
In case someone else comes along, it needs to be lowercase `accept` - [example](https://github.com/CocoaPods/cocoapods-metadata-service/blob/9b0eac5c27309efd714718b0bbc93f2d2baeaf86/source/podspec/uploadREADME.ts#L9-L18)

**Comment by gr2m** [comment]
@orta thanks for sharing and sorry you run into this :( I'm quite sure header names will become case insensitive via #742, I’ll make sure to add a test

**Comment by andrewcarter** [comment]
Apologies for reviving this thread but I have a related question/issue:

Even though the raw content type is specified, the returned `data.content` is still stringified so it's unsuitable to use with binary data it seems. For example, if requesting an image, the binary data will be mangled.

Is there any way to get around this with `octokit/rest`? The only way I found was to set             `mediaType: { format: "object" }` and then un-base64 encode the returned content, which obviously is not optimal.

Otherwise, I may just fetch the raw data directly bypassing `octokit/rest`.

If anyone sees this and happens to reply, much appreciated! 🍺

**Comment by gr2m** [comment]
Hey @andrewcarter, I think this is a legit problem. Could you please create a new issue to track it?

**Comment by andrewcarter** [comment]
Done #1575! Thanks for the quick reply 🍻
