### ISSUE TITLE
Translate asset urls into requests

### ISSUE THREAD

**Issue by jbjonesjr** [octokit/octokit.js#583]
GitHub response objects often return asset urls as part of their payload (such as `https://api.github.com/repos/octocat/Hello-World/issues/1347/comments` from this [sample payload](https://developer.github.com/v3/issues/#list-issues)).

It would be awesome if this sdk could use these urls to make the appropriate requests without making the users parse the url.

In the meantime, I've resorted to helper functions that break down the url into the components the sdk is currently expecting for its requests:

```
  parseCommentURL(url) {
    const match = url.match('https://api.github.com/repos/(.*)/(.*)/issues/(.*)/comments');
    if (match === null) {
      return {};
    } else {
      return {
        owner:match[1],
        repo:match[2],
        number:match[3]
      };
    }
  }
```

This could be implemented either by overloading the sdk methods or creating an additional method for these parameters. Any example of an endpoint that could make use of a url like this is something like http://mikedeboer.github.io/node-github/#api-issues-getComments

originally requested by @wilhelm in probot-slack: https://probot-talk.slack.com/archives/C6S4FC8AF/p1504269385000439

cc/ @gr2m

**Comment by gr2m** [comment]
I would probably implement this in a separate module first. Even if we end up using it in the github library, we’d still use an external library because why not, this seems useful to other use cases, too :)

Knowing npm, this might even already exists :) My thinking is that modularity is normal in JS land, and at least for more advanced users who built front-end applications where library size matters, I’d see if we can make it optional.

So in your example would be something like this

```js
github.issues.getComments(
  githubParseUrl('https://api.github.com/repos/octocat/Hello-World/issues/1347/comments')
)
```

What do you think?

**Comment by wilhelmklopp** [comment]
Thanks for posting this @jbjonesjr :)

I feel like parsing the URLs might be harder than it seems at first, just because there are so many different URLS. There are quite a [few NPM packages](https://www.npmjs.com/search?q=parse+github+url) that attempt to do this, and when I was last looking for a GitHub url parser (for an unrelated use-case, actually :P) none of them were quite able to get the job done. 

Another, simpler and less powerful way of solving this problem is by having a separate method in this library that just takes the URL and makes an authenticated request to it. This would have sufficed for the use-case that sparked this feature request.

Having said that, it would be _super_ nice to have a well functioning GitHub URL parser 💯

**Comment by gr2m** [comment]
> a separate method in this library that just takes the URL and makes an authenticated request to it

This sounds interesting. You mean a separate method like `github.request(url, options)` where `url` woudl be a full url to the API endpoint, and options could include `method`, `data` for PUT/PATCH/POST requests and maybe custom headers? And it would send the authentication configured for the `github` client?

**Comment by wilhelmklopp** [comment]
Yep, exactly 👍 
That would have been really nice to use

**Comment by gr2m** [comment]
> Having said that, it would be super nice to have a well functioning GitHub URL parser 💯

Just wanting to mention that this is a very good point. The same is probably true for other languages. As URL templates are so important to GitHub’s REST API, I think we should make them either part of the toolkits, or make separate officially supported libraries.

**Comment by gr2m** [comment]
There is now [`octokit.request`](https://github.com/octokit/rest.js/tree/master/lib/request). 

⚠️🚨 note that this is not considered public API yet, it might change at any time, so make sure to pin the `@octokit/rest` version in your package.json if you want to work with it

**Comment by gr2m** [comment]
[v16](https://github.com/octokit/rest.js/pull/1052) makes the plugin API public, so you could build a plugin that adds this feature. I’d be a cool experiment!

**Comment by gr2m** [comment]
I’ll close it due to lack of activity. I also don’t see a use case myself. But if anyone would like to build such a thing I’d be happy to help out
