### ISSUE TITLE
Confusing ref parameter between createReference and deleteReference

### ISSUE THREAD

**Issue by SamyPesse** [octokit/octokit.js#813]
This module exposes two methods: `createReference` and `deleteReference`, both are accepting a parameter `ref`, but both are not accepting the same format:

```js
await octokit.gitdata.createReference({
    owner,
    repo,
    ref: 'refs/head/hello',
    sha
});

await octokit.gitdata.deleteReference({
    owner,
    repo,
    ref: 'head/hello'
});
```

The main reason is that `createReference` pass the `ref` parameters to the body of the POST for [`POST /repos/:owner/:repo/git/refs`](https://developer.github.com/v3/git/refs/#create-a-reference). While for `deleteReference`, the `ref` parameter is included in the url that already contains the `refs/` prefix: [`DELETE /repos/:owner/:repo/git/refs/:ref`](https://developer.github.com/v3/git/refs/#delete-a-reference).

I'm suggesting normalizing this parameter in the library to only accept `refs/head/hello` or `head/hello`.

**Comment by SamyPesse** [comment]
`updateReference` is also only accepting `head/hello` (like `deleteReference`).

**Comment by gr2m** [comment]
I’ve run into this myself a few times. It’s tempting to "fix" this with the Octokit libraries wrapping the REST API, but any deviation makes makes it harder to maintain and has a risk of confusion. So in general we have the rule of sticking to the REST API as close as possible, with all its design flaws.

For the JavaScript Octokit specifically it will be hard to implement any kind of deviation because all the endpoint methods are generated from a JSON file ([`lib/routes.json`](https://github.com/octokit/rest.js/blob/master/lib/routes.json)) which I hope to get auto-generated and -updated soon based on the latest API docs at https://developer.github.com/v3/

I actually don’t know the thinking behind this one, could you check in with support@github.com? Maybe there is a good reason we don’t see right now. Maybe they could at least improve the API docs to make that clear
