### ISSUE TITLE
How to use streaming in createfile and updatefile

### ISSUE THREAD

**Issue by andhure** [octokit/octokit.js#887]
Hello,

I was trying to stream and upload a file to a repo using create file. Below is the code, I was trying:

```js
try{
        let response = await octokit.repos.createFile({
            owner: "owner",
            repo: "reponame",
            path:  "lib/test.js",
            branch:"dev",
            message: 'Commit Message',
            content: new Buffer(fs.createReadStream('test.js')).toString('base64'), 
            author: {
                "name": "test-author",
                "email": "test-author@test.com"
            }
        })
    }
```

I get the error: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

Is it possible to stream foe this api?

**Comment by gr2m** [comment]
Hi @andhure 👋 I don’t think that this API can be streamed because the content of the file is namespaced with the property name "content": https://developer.github.com/v3/repos/contents/#create-a-file

The only API that can be streamed is [Upload a release asset](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) because the raw content of the file can be sent in the file body. We are testing that here: https://github.com/octokit/rest.js/blob/469991db293b8ffc2af6daec0bb35665793a916d/test/unit/upload-asset-test.js#L21-L27

But that’s a good question. Maybe uploading the raw content and setting the `Content-Type` header accordingly would work and the only thing missing is documentation for it. You could test that by using the `octokit.request` method, see https://github.com/octokit/rest.js/tree/master/lib/request or maybe directly the request library that we use internally: https://github.com/bitinn/node-fetch

If it does not work it might be worth asking support@github.com about it. Reference this issue if you do and keep us posted :)

**Comment by andhure** [comment]
Thanks gr2m for the quick update. I will try this and update you if there is any progress.
