### ISSUE TITLE
using a single instance with multiple authentications

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#898]
The current [octokit.authenticate](https://github.com/octokit/rest.js/tree/347b59d767a8250f8f70f1ba025894c0622d396f#authentication) method is mutating the internal state so that all following requests are using the set authentication method. That is a problem when handling e.g. multiple users or different installations of an app. For example, [probot creates a new instance of GitHub](https://github.com/probot/probot/blob/d2fe925e1aeade9168d3042be25d0a7c48264938/src/robot.ts#L162-L184) each time it handles a request.

One way to approach it would be to make the internal state immutable and have `octokit.authenticate` return a new scoped instance instead.

Before

```js
octokit.authenticate({
  type: 'token',
  token: 'secrettoken123'
})
octokit.orgs.get({org: 'octokit'})
```

After

```js
const user123 = octokit.authenticate({
  type: 'token',
  token: 'secrettoken123'
})
user123.orgs.get({org: 'octokit'})
```

/cc @bkeepers @andymckay

**Comment by bkeepers** [comment]
I don't have any strong feels either way. They both seem comparable to me since they both have to return a new instance of the client at some point, with the only difference being where the new instance is returned from.

And as long as prototypical inheritance is being used, there shouldn't be any performance implications for instantiating a new client.

**Comment by gr2m** [comment]
One thing that I want to make sure is that there will be a single place to register plugins for both Probot and people building apps with Probot, and that the instance passed to the event handlers has the registered plugins.

**Comment by gr2m** [comment]
`octokit.authenticate` is deprecated, it was replaced by a `new Octokit({ auth })` constructor option

**Comment by johnsonsamuel** [comment]
@gr2m I did use the following method for authenticating but I am unable to update a check run because I get an error `Invalid app_id`

## Below code is for authenitcation:

```js
const octokit = new Octokit({
    async auth() {
      return `token ${installationAccessToken}`
    }
  });
```

## This is code for updating a check run
 
```js
octokit.checks.update({
    owner: owner,
    repo: repo,
    check_run_id: checkRunId,
    conclusion: 'failure'
  })
```

But I get the following error,

```
HttpError: {"message":"Invalid app_id `APPID`","documentation_url":"https://developer.github.com/v3/checks/runs/#update-a-check-run"}
      at response.text.then.message (node_modules/probot/node_modules/@octokit/rest/lib/request/request.js:72:19)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Can you please let me know if I am missing something ?

**Comment by gr2m** [comment]
Could you create a new issue in future? Your problem is unrelated to this issue, and it's already closed.

`Invalid app_id` indicates that there is a problem with your `installationAccessToken`. How did you calculate it?
