### ISSUE TITLE
Documentation for using the getMigrationArchiveLink function?

### ISSUE THREAD

**Issue by sgvictorino** [octokit/octokit.js#915]
Is there any documentation or example showing how to use the `getMigrationArchiveLink` function to successfully fetch the archive download link?
I'm asking because the response I get from the library is quite different from what the response should be according to the [API docs](https://developer.github.com/v3/migrations/orgs/#download-a-migration-archive). Instead of an S3 link in the response, I get a data buffer and the headers:
```
{ data: <Buffer 1f 8b 08 00 67 58 21 5b 00 03 ec 5b 07 5c 14 d7 d6 c7 04 23 58 10 13 7b f4 39 ac 1d d8 dd 29 db 51 a3 62 89 82 e2 13 44 05 14 67 77 87 dd 81 dd 99 75 ... >,
  status: 200,
  headers:
   { 'accept-ranges': 'bytes',
     'cache-control': 'max-age=2592000',
     connection: 'close',
     'content-disposition': 'filename=a4c44cec-6f31-11e8-98c7-a504e98ea25a.tar.gz',
     'content-length': '56091',
     'content-type': 'application/x-gzip',
     date: 'Wed, 13 Jun 2018 19:32:34 GMT',
     etag: '"076cb43e1ee3a4551a6a11e4e83d0dbd"',
     'last-modified': 'Wed, 13 Jun 2018 17:46:16 GMT',
     server: 'AmazonS3',
     'x-amz-id-2': 'NnWJE6FrESNjRaagpT3jrVSDKwcM3odqfAs5Vh6ypgOeKhTX6isIcDeEWCI6RRNGhHAxwiRLXNY=',
     'x-amz-meta-surrogate-control': 'max-age=31557600',
     'x-amz-request-id': '46E5B85E51AA66C8' },
  meta: [Getter] }
```
What can I do to get the link? Thanks in advance!

**Comment by gr2m** [comment]
We had some discussion on the get*Link methods, it’s tricky for JavaScript. We want the library to work the same in both Node.js and browser, and browsers automatically follow redirects. So instead of the link, you get the response of the final redirect. You can follow the discussion at https://github.com/octokit/rest.js/issues/881, I also suggest a workaround there.

Okay if we close this issue in favor of #881?

**Comment by sgvictorino** [comment]
Sounds good!
