### ISSUE TITLE
octokit.migrations.unlockRepoForAuthenticatedUser() returns 404

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#925]
follow up issue for https://github.com/octokit/rest.js/pull/921#issuecomment-397833187
/cc @bitsol

**Comment by sgvictorino** [comment]
@gr2m over the next week I'll be building a script to unlock my repos (😆 see https://github.com/octokit/rest.js/pull/921#issuecomment-397837453) , so I should be able to tell you if it works for me.

Also:

The problem can't be because of an incorrect state on the part of the migration: https://asciinema.org/a/60v8qI9woD9bRmyY8ox66hNyI?t=10

**Comment by sgvictorino** [comment]
I built the script at bitsol/migrate-github#2, and the 404 codes were returned for most of the repositories (as can be expected), but the intended behavior overall was achieved (I can push code now! :tada:) and the "test" was much more thorough than the previous ones.

If no one else has any problems with it either @gr2m, I can close this issue.

**Comment by gr2m** [comment]
Sounds good to me :) Thanks a lot for all your help 👍
