### ISSUE TITLE
octokit.issues.addLabels() documentation is missing "labels" parameter

### ISSUE THREAD

**Issue by KingAkeem** [octokit/octokit.js#934]
[This](https://octokit.github.io/rest.js/#api-Issues-addLabels) section of your docs is missing one of the needed parameters. In order to add labels, you must also pass a `label` property that contains an array of strings that represents the labels to be added.

**Comment by gr2m** [comment]
Thanks Akeem for reporting that issue.

The reason why the `labels` property is not listed is because the API documentation is generated automatically from v3 REST API documentation, and the "[Add labels to an issue](https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue)" section does not have a parameter table like for example "[Update a label](https://developer.github.com/v3/issues/labels/#update-a-label)". The challenge here is that the current route handle for `POST /repos/:owner/:repo/issues/:number/labels` expects an array at the root label:

```json
[
  "Label1",
  "Label2"
]
```

Instead of a JSON object with properties like most of the others. But the API team & docs team is aware of this and they are trying to normalize the event handlers so that each of them will accept an object, e.g. in this case

```json
{
  "labels": [
    "Label1",
    "Label2"
  ]
}
```

Once we have that, we can add a parameter table and the whole automation will work again.

I can workaround these bugs in `lib/routes.json`, e.g. https://github.com/octokit/rest.js/blob/f54006738edfb7ef494d97f23ca6b7a49b934a80/lib/routes.json#L2766-L2774

But adding the `labels` parameter to the API docs will be more complicated because they are entirely generated based on https://github.com/octokit/routes

I think it’s not worth the effort as it will be resolved once the route handlers are normalized and the v3 API docs are updated.
