### ISSUE TITLE
Add getLatestTag() method

### ISSUE THREAD

**Issue by bnb** [octokit/octokit.js#952]
I've built out a [Twitter bot](https://twitter.com/nodekitten) that tweets when new releases of the Node.js project happen. It's built with Octokit/rest.js, Twit, and Node.js.

Currently I'm using the `getLatestRelease()` method to actually snag the metadata I need. Unfortunately, after the first deploy and successful tweet of the bot I realized that the process of Node.js doesn't necessarily follow how I'd expect getLatestRelease to work – it more follows what a theoretical getLatestTag method would do.

Node.js currently tags and then promotes to a release _as soon as possible_ but not always instantly. That said, tagging is effectively when communication about a new release begins rather than when a tag is marked as a release.

As such, I'd really love to be able to have a `getLatestTag()` method that solely returns the latest git tag from any given repo. _Ideally_ the API would be very similar to `getLatestRelease()`, returning the tag's `html_url` and the `tag_name` plus the additional available metadata 🤗

**Comment by gr2m** [comment]
We want to keep `@octokit/rest` very closely aligned to the existing APIs documented at https://developer.github.com/v3/, and unfortunately there is no route endpoint to get the latest tag, you’d need to build it yourself.

You’d probably need to get all tags with https://octokit.github.io/rest.js/#api-Repos-getTags, the response seems to be sorted oldest -> newest, so you could do https://api.github.com/repos/octokit/rest.js/tags?per_page=1

The code for that would look like this

```js
const {data: [latestTag]} = await client.repos.getTags({owner: 'octokit', repo: 'rest.js', per_page: 1})
console.log(latestTag)
```

does that work for you?

In order to enable the community to build functionality beyond GitHub’s v3 REST API I plan to make the plugin API public soon, as described at https://github.com/octokit/rest.js/tree/master/lib/plugins, I don’t expect it to break. In your case, the plugin would do the underlying requests transparently, so users would have an `client.getLatestTag({owner, repo})` method, for example.
