### ISSUE TITLE
"details_url" is not a valid value for conclusion of create/update check

### ISSUE THREAD

**Issue by foolip** [octokit/octokit.js#958]
Incorrect docs here:
https://octokit.github.io/rest.js/#api-Checks-create
https://octokit.github.io/rest.js/#api-Checks-update

Both say "Allowed values: success, failure, neutral, cancelled, timed_out, action_required, details_url" but the final "details_url" isn't an allowed value. Attempting to use it will result in this error:
```
HttpError: {"message":"Invalid request.\n\ndetails_url is not a member of [\"success\", \"failure\", \"neutral\", \"cancelled\", \"timed_out\", \"action_required\"].","documentation_url":"https://developer.github.com/v3/checks/runs/#create-a-check-run"}
```

https://github.com/octokit/routes/issues/199 is possibly root cause, but there are extra invalid enum values there, so perhaps not.

**Comment by foolip** [comment]
But are the docs I linked to generated from that source? Why don't the other incorrect enum values also show up if so?

**Comment by gr2m** [comment]
> Why don't the other incorrect enum values also show up if so?

You mean why they don’t show up in the parameter description? That is because we show the same description that you see on the API docs (e.g. https://developer.github.com/v3/checks/runs/#create-a-check-run). The enum values are extracted using a regex, which does not match the particular description of these endpoints

I’m working with the docs team to fix it on the documentation page itself, which will then automatically update https://github.com/octokit/routes (it runs a nightly cron job that scrapes the v3 REST API docs) which will publish a new version of https://www.npmjs.com/package/@octokit/routes which will create a new pull request on this repository thanks to Greenkeeper which then will publish a new version of `@octokit/rest` when merged.

If this is a blocking issue for you then you can look into the code that looks for enum values in parameter descriptions and adopt it so that it reads the allowed values correctly from the `conclusion` parameter description

**Comment by foolip** [comment]
> You mean why they don’t show up in the parameter description? That is because we show the same description that you see on the API docs (e.g. https://developer.github.com/v3/checks/runs/#create-a-check-run). The enum values are extracted using a regex, which does not match the particular description of these endpoints

Right, why only one of the extra values shows up in https://octokit.github.io/rest.js/#api-Checks-create.

It's amusing to see how "Note: Providing conclusion will automatically set the status parameter to completed." turned into extra enum values like that :)

> If this is a blocking issue for you

No, I just wanted to report since it seemed different from the existing issue.

**Comment by gr2m** [comment]
> It's amusing to see how "Note: Providing conclusion will automatically set the status parameter to completed." turned into extra enum values like that :)

It’s all regular expression :) Some of them are rather complex
