### ISSUE TITLE
Pre-receive hooks endpoints missing

### ISSUE THREAD

**Issue by Eddman** [octokit/octokit.js#986]
The API and `routes.json` contain methods for administration of pre-receive hooks defined in:
https://developer.github.com/enterprise/2.14/v3/enterprise-admin/pre_receive_hooks/

But the repository settings for pre-receive hooks defined in the following spec are missing completely:
https://developer.github.com/enterprise/2.14/v3/repos/pre_receive_hooks/

**Comment by gr2m** [comment]
The reason why these are missing is that [octokit/routes](https://github.com/octokit/routes) does not record the enterprise routes yet. Once we have the plugin API ready, we plan to create a separate module for the enterprise routes, because they bloat up the routes.json file a lot while most people don’t need them.

For the time being, you can send a PR to add "Repository Pre-receive Hooks for Enterprise" to the routes.json file

**Comment by Eddman** [comment]
@gr2m Under `repos`?

**Comment by gr2m** [comment]
yes

**Comment by Eddman** [comment]
PR #987 opened...

**Comment by gr2m** [comment]
I’m very sorry that I didn’t get to ship this, once we have the plugin for the enterprise routes they will be kept up-to-date just like this library. See also https://github.com/octokit/rest.js/pull/987#issuecomment-431388986
